### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by musm**
fix osx on ci, could we tag after this?

### CODE REVIEW

**Comment by musm** [comment]
cc @ahojukka5

**Comment by ahojukka5** [comment]
Hmm any idea why the coverage decreased.

**Comment by musm** [comment]
probably just a fluke?

**Comment by musm** [comment]
I enabled osx, to show that with these changes osx builds pass on travis

**Comment by musm** [comment]
@ahojukka5 this seems pretty uncontroversial. I propose we merge this. Coveralls is always a bit flaky and unreliable at times.

**Comment by ahojukka5** [comment]
Yes. Let's just merge.

**Pull request merged**
